### ISSUE TITLE
vue 3 compatibility

### ISSUE THREAD

**Issue by PaddyLock** [danielroe/stream-vue#83]
**🐛 The bug**
Does not load VideoStream player with Vue 3 and throws this error

Uncaught (in promise) TypeError: h is not a function
    at Proxy.render (index.es.js:81:9)

**🛠️ To reproduce**
use VideoStream with vue 3

**🌈 Expected behaviour**
The player to load

**ℹ️ Additional context**

**Comment by danielroe** [comment]
This library is currently written for Vue 2. I'd welcome a PR to update it to Vue 3, or I'll aim to update it later.

**Comment by fenn1ks** [comment]
> This library is currently written for Vue 2. I'd welcome a PR to update it to Vue 3, or I'll aim to update it later.

Hi! Can you tell me how to do this? need a module for vue 3
